CREATE TABLE bookmarks_table (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    url TEXT NOT NULL,
    rating decimal(12,2) NOT NULL,
    date_published TIMESTAMPTZ default now() NOT NULL 
);